extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\0','E:\temp\Final_CNN\Final_CNN\test\0')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\1','E:\temp\Final_CNN\Final_CNN\test\1')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\2','E:\temp\Final_CNN\Final_CNN\test\2')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\3','E:\temp\Final_CNN\Final_CNN\test\3')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\4','E:\temp\Final_CNN\Final_CNN\test\4')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\5','E:\temp\Final_CNN\Final_CNN\test\5')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\6','E:\temp\Final_CNN\Final_CNN\test\6')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\7','E:\temp\Final_CNN\Final_CNN\test\7')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\8','E:\temp\Final_CNN\Final_CNN\test\8')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_test\9','E:\temp\Final_CNN\Final_CNN\test\9')


extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\0','E:\temp\Final_CNN\Final_CNN\train\0')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\1','E:\temp\Final_CNN\Final_CNN\train\1')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\2','E:\temp\Final_CNN\Final_CNN\train\2')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\3','E:\temp\Final_CNN\Final_CNN\train\3')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\4','E:\temp\Final_CNN\Final_CNN\train\4')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\5','E:\temp\Final_CNN\Final_CNN\train\5')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\6','E:\temp\Final_CNN\Final_CNN\train\6')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\7','E:\temp\Final_CNN\Final_CNN\train\7')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\8','E:\temp\Final_CNN\Final_CNN\train\8')
extract('E:\temp\Final_CNN\Final_CNN\CIFAR10_Images_train\9','E:\temp\Final_CNN\Final_CNN\train\9')